### Import necessary packages
---
We have used the numpy, pandas, matplotlib

In [168]:
import numpy as np
import pandas as pd
import datetime as dt
import os
import pathlib

In [169]:
plantData = {
    "Plant1G": "../Data/Plant_1_Generation_Data.csv",
    "Plant1W": "../Data/Plant_1_Weather_Sensor_Data.csv",
    "Plant2G": "../Data/Plant_2_Generation_Data.csv",
    "Plant2W": "../Data/Plant_2_Weather_Sensor_Data.csv",
}

In [170]:
plant1Genration = pd.read_csv(plantData["Plant1G"])
plant1Weather = pd.read_csv(plantData["Plant1W"])
plant2Genration = pd.read_csv(plantData["Plant2G"])
plant2Weather = pd.read_csv(plantData["Plant2W"])

dataDict1 = {
    "plant1": [plant1Genration, plant1Weather],
    "plant2": [plant2Genration, plant2Weather],
}

dataDict2 = {
    "generation": [plant1Genration, plant2Genration],
    "weather": [plant1Weather, plant2Weather],
}

In [171]:
# plant1Genration.info()
plant1Genration["DATE_TIME"] = pd.to_datetime(plant1Genration["DATE_TIME"])
plant1Genration.sort_values(by=["SOURCE_KEY", "DATE_TIME"])

,DATE_TIME,PLANT_ID,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD
33112,2020-01-06 00:00:00,4135001,1BY6WEcLGh8j5v7,0.0,0.0,829.0,6377931.0
33134,2020-01-06 00:15:00,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.0,6377931.0
33156,2020-01-06 00:30:00,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.0,6377931.0
33178,2020-01-06 00:45:00,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.0,6377931.0
33200,2020-01-06 01:00:00,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.0,6377931.0
...,...,...,...,...,...,...,...
58173,2020-12-06 22:45:00,4135001,zVJPv84UY57bAof,0.0,0.0,5863.0,7328550.0
58195,2020-12-06 23:00:00,4135001,zVJPv84UY57bAof,0.0,0.0,5863.0,7328550.0
58217,2020-12-06 23:15:00,4135001,zVJPv84UY57bAof,0.0,0.0,5863.0,7328550.0
58239,2020-12-06 23:30:00,4135001,zVJPv84UY57bAof,0.0,0.0,5863.0,7328550.0
58261,2020-12-06 23:45:00,4135001,zVJPv84UY57bAof,0.0,0.0,5863.0,7328550.0

In [172]:
sourceKey = plant1Genration['SOURCE_KEY'].unique()
startDateTime = plant1Genration["DATE_TIME"].iat[0]
endDateTime = plant1Genration["DATE_TIME"].iat[-1]

endDateTime

Timestamp('2020-06-17 23:45:00')

In [186]:
k = plant1Genration[plant1Genration["SOURCE_KEY"] == "zVJPv84UY57bAof"]
start_date = "2020-05-15 15:00:00"
end_date = "2020-05-15 18:00:00"
mask = (k["DATE_TIME"] >= start_date) & (k["DATE_TIME"] < end_date)
k = k.loc[mask]
# col_list= ['SOURCE_KEY', 'DC_POWER', 'AC_POWER', 'DAILY_YIELD', 'TOTAL_YIELD']
# k.groupby(['DATE_TIME']).sum()
k = k.set_index('DATE_TIME') 
testings=k[['AC_POWER']].resample('H').mean()
testings


# sourceKey = plant1Genration['SOURCE_KEY'].unique()
# df = pd.DataFrame()
# for x in sourceKey:
#     k = plant1Genration[plant1Genration["SOURCE_KEY"] == x]
#     k = k.set_index('DATE_TIME')
#     testings=k[['AC_POWER']].resample('H').mean()
#     print(testings)

                       AC_POWER
DATE_TIME
2020-05-15 15:00:00  600.366071
2020-05-15 16:00:00  454.360268
2020-05-15 17:00:00  155.950446

In [174]:
k

,PLANT_ID,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD
DATE_TIME,,,,,,
2020-05-15 15:00:00,4135001,zVJPv84UY57bAof,6074.500000,595.262500,4829.875000,7120980.875
2020-05-15 15:15:00,4135001,zVJPv84UY57bAof,5732.428571,561.800000,4985.857143,7121136.857
2020-05-15 15:30:00,4135001,zVJPv84UY57bAof,7732.714286,756.914286,5128.571429,7121279.571
2020-05-15 15:45:00,4135001,zVJPv84UY57bAof,4972.875000,487.487500,5275.000000,7121426.000

In [183]:
# dateTime = k["DATE_TIME"].iat[0]
plantID = k["PLANT_ID"].iat[0]
sourceKey = k["SOURCE_KEY"].iat[0]
dcPower = k["DC_POWER"].sum()
acPower = k["AC_POWER"].sum()
dailyYield = k["DAILY_YIELD"].iat[-1]
totalYield = k["TOTAL_YIELD"].iat[-1]

In [ ]:
abc = pd.DataFrame(
    [[dateTime, plantID, sourceKey, dcPower, acPower, dailyYield, totalYield]],
    columns=[
        "DATE_TIME",
        "PLANT_ID",
        "SOURCE_KEY",
        "DC_POWER",
        "AC_POWER",
        "DAILY_YIELD",
        "TOTAL_YIELD",
    ],
)
abc

,DATE_TIME,PLANT_ID,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD
0,2020-05-15 15:00:00,4135001,zVJPv84UY57bAof,24512.517857,2401.464286,5275.0,7121426.0

In [ ]:
startDate = "2020-05-15 15:00:00"
endDate = "2020-05-15 16:00:00 "

startDate = dt.datetime(2020,5,15,0,0,0)
endDate = dt.datetime(2020,5,17,0,15,0)
seconds = (endDate - startDate).total_seconds()
step = dt.timedelta(minutes=15)
array = []
for i in range(0, int(seconds), int(step.total_seconds())):
    array.append(startDate + dt.timedelta(seconds=i))
array = [i.strftime("%Y-%m-%d %H:%M:%S") for i in array]
array
uniqueYear = pd.to_datetime(plant1Genration['DATE_TIME']).dt.year.unique()
uniqueMonth = pd.to_datetime(plant1Genration['DATE_TIME']).dt.month.unique()
uniqueDay = pd.to_datetime(plant1Genration['DATE_TIME']).dt.day.unique()

for month in uniqueMonth:
    for day in uniqueDay:
        sd = f'dt.datetime(2020,{month},{day},0,0,0)'
        if day == 31:
            ed = f'dt.datetime(2020,{month},1,0,0,0)'
        else:
            ed = f'dt.datetime(2020,{month},{day},0,0,0)'
        print('month: ', month, " day: ", day)
        print(sd)

# startDateTime = plant1Genration["DATE_TIME"].iat[0]
# endDateTime = plant1Genration["DATE_TIME"].iat[-1]
# k = start_date.to_pydatetime()
# pd.date_range(startDateTime,endDateTime,freq='15min')

month:  5  day:  15
dt.datetime(2020,5,15,0,0,0)
month:  5  day:  16
dt.datetime(2020,5,16,0,0,0)
month:  5  day:  17
dt.datetime(2020,5,17,0,0,0)
month:  5  day:  18
dt.datetime(2020,5,18,0,0,0)
month:  5  day:  19
dt.datetime(2020,5,19,0,0,0)
month:  5  day:  20
dt.datetime(2020,5,20,0,0,0)
month:  5  day:  21
dt.datetime(2020,5,21,0,0,0)
month:  5  day:  22
dt.datetime(2020,5,22,0,0,0)
month:  5  day:  23
dt.datetime(2020,5,23,0,0,0)
month:  5  day:  24
dt.datetime(2020,5,24,0,0,0)
month:  5  day:  25
dt.datetime(2020,5,25,0,0,0)
month:  5  day:  26
dt.datetime(2020,5,26,0,0,0)
month:  5  day:  27
dt.datetime(2020,5,27,0,0,0)
month:  5  day:  28
dt.datetime(2020,5,28,0,0,0)
month:  5  day:  29
dt.datetime(2020,5,29,0,0,0)
month:  5  day:  30
dt.datetime(2020,5,30,0,0,0)
month:  5  day:  31
dt.datetime(2020,5,31,0,0,0)
month:  5  day:  6
dt.datetime(2020,5,6,0,0,0)
month:  5  day:  13
dt.datetime(2020,5,13,0,0,0)
month:  5  day:  14
dt.datetime(2020,5,14,0,0,0)
month:  1  day:  15
dt.datetime(2020,1,15,0,0,0)
month:  1  day:  16
dt.datetime(2020,1,16,0,0,0)
month:  1  day:  17
dt.datetime(2020,1,17,0,0,0)
month:  1  day:  18
dt.datetime(2020,1,18,0,0,0)
month:  1  day:  19
dt.datetime(2020,1,19,0,0,0)
month:  1  day:  20
dt.datetime(2020,1,20,0,0,0)
month:  1  day:  21
dt.datetime(2020,1,21,0,0,0)
month:  1  day:  22
dt.datetime(2020,1,22,0,0,0)
month:  1  day:  23
dt.datetime(2020,1,23,0,0,0)
month:  1  day:  24
dt.datetime(2020,1,24,0,0,0)
month:  1  day:  25
dt.datetime(2020,1,25,0,0,0)
month:  1  day:  26
dt.datetime(2020,1,26,0,0,0)
month:  1  day:  27
dt.datetime(2020,1,27,0,0,0)
month:  1  day:  28
dt.datetime(2020,1,28,0,0,0)
month:  1  day:  29
dt.datetime(2020,1,29,0,0,0)
month:  1  day:  30
dt.datetime(2020,1,30,0,0,0)
month:  1  day:  31
dt.datetime(2020,1,31,0,0,0)
month:  1  day:  6
dt.datetime(2020,1,6,0,0,0)
month:  1  day:  13
dt.datetime(2020,1,13,0,0,0)
month:  1  day:  14
dt.datetime(2020,1,14,0,0,0)
month:  2  day:  15
dt.datetime(2020,2,15,0,0,0)
month:  2  day:  16
dt.datetime(2020,2,16,0,0,0)
month:  2  day:  17
dt.datetime(2020,2,17,0,0,0)
month:  2  day:  18
dt.datetime(2020,2,18,0,0,0)
month:  2  day:  19
dt.datetime(2020,2,19,0,0,0)
month:  2  day:  20
dt.datetime(2020,2,20,0,0,0)
month:  2  day:  21
dt.datetime(2020,2,21,0,0,0)
month:  2  day:  22
dt.datetime(2020,2,22,0,0,0)
month:  2  day:  23
dt.datetime(2020,2,23,0,0,0)
month:  2  day:  24
dt.datetime(2020,2,24,0,0,0)
month:  2  day:  25
dt.datetime(2020,2,25,0,0,0)
month:  2  day:  26
dt.datetime(2020,2,26,0,0,0)
month:  2  day:  27
dt.datetime(2020,2,27,0,0,0)
month:  2  day:  28
dt.datetime(2020,2,28,0,0,0)
month:  2  day:  29
dt.datetime(2020,2,29,0,0,0)
month:  2  day:  30
dt.datetime(2020,2,30,0,0,0)
month:  2  day:  31
dt.datetime(2020,2,31,0,0,0)
month:  2  day:  6
dt.datetime(2020,2,6,0,0,0)
month:  2  day:  13
dt.datetime(2020,2,13,0,0,0)
month:  2  day:  14
dt.datetime(2020,2,14,0,0,0)
month:  3  day:  15
dt.datetime(2020,3,15,0,0,0)
month:  3  day:  16
dt.datetime(2020,3,16,0,0,0)
month:  3  day:  17
dt.datetime(2020,3,17,0,0,0)
month:  3  day:  18
dt.datetime(2020,3,18,0,0,0)
month:  3  day:  19
dt.datetime(2020,3,19,0,0,0)
month:  3  day:  20
dt.datetime(2020,3,20,0,0,0)
month:  3  day:  21
dt.datetime(2020,3,21,0,0,0)
month:  3  day:  22
dt.datetime(2020,3,22,0,0,0)
month:  3  day:  23
dt.datetime(2020,3,23,0,0,0)
month:  3  day:  24
dt.datetime(2020,3,24,0,0,0)
month:  3  day:  25
dt.datetime(2020,3,25,0,0,0)
month:  3  day:  26
dt.datetime(2020,3,26,0,0,0)
month:  3  day:  27
dt.datetime(2020,3,27,0,0,0)
month:  3  day:  28
dt.datetime(2020,3,28,0,0,0)
month:  3  day:  29
dt.datetime(2020,3,29,0,0,0)
month:  3  day:  30
dt.datetime(2020,3,30,0,0,0)
month:  3  day:  31
dt.datetime(2020,3,31,0,0,0)
month:  3  day:  6
dt.datetime(2020,3,6,0,0,0)
month:  3  day:  13
dt.datetime(2020,3,13,0,0,0)
month:  3  day:  14
dt.datetime(2020,3,14,0,0,0)
month:  4  day:  15
dt.datetime(2020,4,15,0,0,0)
month:  4  day:  16
dt.datetime(2020,4,16,0,0,0)
month:  4  day:  17
dt.datetime(2020,4,17,0,0,0)
month:  4  day:  18
dt.datetime(2020,4,18,0,0,0)
month:  4  day:  19
dt.datetime(2020,4,19,0,0,0)
month:  4  day:  20
dt.datetime(2020,4,20,0,0,0)
month:  4  day:  21
dt.datetime(2020,4,21,0,0,0)
month:  4  day:  22
dt.datetime(2020,4,22,0,0,0)
month:  4  day:  23
dt.datetime(2020,4,23,0,0,0)
month:  4  day:  24
dt.datetime(2020,4,24,0,0,0)
month:  4  day:  25
dt.datetime(2020,4,25,0,0,0)
month:  4  day:  26
dt.datetime(2020,4,26,0,0,0)
month:  4  day:  27
dt.datetime(2020,4,27,0,0,0)
month:  4  day:  28
dt.datetime(2020,4,28,0,0,0)
month:  4  day:  29
dt.datetime(2020,4,29,0,0,0)
month:  4  day:  30
dt.datetime(2020,4,30,0,0,0)
month:  4  day:  31
dt.datetime(2020,4,31,0,0,0)
month:  4  day:  6
dt.datetime(2020,4,6,0,0,0)
month:  4  day:  13
dt.datetime(2020,4,13,0,0,0)
month:  4  day:  14
dt.datetime(2020,4,14,0,0,0)
month:  6  day:  15
dt.datetime(2020,6,15,0,0,0)
month:  6  day:  16
dt.datetime(2020,6,16,0,0,0)
month:  6  day:  17
dt.datetime(2020,6,17,0,0,0)
month:  6  day:  18
dt.datetime(2020,6,18,0,0,0)
month:  6  day:  19
dt.datetime(2020,6,19,0,0,0)
month:  6  day:  20
dt.datetime(2020,6,20,0,0,0)
month:  6  day:  21
dt.datetime(2020,6,21,0,0,0)
month:  6  day:  22
dt.datetime(2020,6,22,0,0,0)
month:  6  day:  23
dt.datetime(2020,6,23,0,0,0)
month:  6  day:  24
dt.datetime(2020,6,24,0,0,0)
month:  6  day:  25
dt.datetime(2020,6,25,0,0,0)
month:  6  day:  26
dt.datetime(2020,6,26,0,0,0)
month:  6  day:  27
dt.datetime(2020,6,27,0,0,0)
month:  6  day:  28
dt.datetime(2020,6,28,0,0,0)
month:  6  day:  29
dt.datetime(2020,6,29,0,0,0)
month:  6  day:  30
dt.datetime(2020,6,30,0,0,0)
month:  6  day:  31
dt.datetime(2020,6,31,0,0,0)
month:  6  day:  6
dt.datetime(2020,6,6,0,0,0)
month:  6  day:  13
dt.datetime(2020,6,13,0,0,0)
month:  6  day:  14
dt.datetime(2020,6,14,0,0,0)
month:  7  day:  15
dt.datetime(2020,7,15,0,0,0)
month:  7  day:  16
dt.datetime(2020,7,16,0,0,0)
month:  7  day:  17
dt.datetime(2020,7,17,0,0,0)
month:  7  day:  18
dt.datetime(2020,7,18,0,0,0)
month:  7  day:  19
dt.datetime(2020,7,19,0,0,0)
month:  7  day:  20
dt.datetime(2020,7,20,0,0,0)
month:  7  day:  21
dt.datetime(2020,7,21,0,0,0)
month:  7  day:  22
dt.datetime(2020,7,22,0,0,0)
month:  7  day:  23
dt.datetime(2020,7,23,0,0,0)
month:  7  day:  24
dt.datetime(2020,7,24,0,0,0)
month:  7  day:  25
dt.datetime(2020,7,25,0,0,0)
month:  7  day:  26
dt.datetime(2020,7,26,0,0,0)
month:  7  day:  27
dt.datetime(2020,7,27,0,0,0)
month:  7  day:  28
dt.datetime(2020,7,28,0,0,0)
month:  7  day:  29
dt.datetime(2020,7,29,0,0,0)
month:  7  day:  30
dt.datetime(2020,7,30,0,0,0)
month:  7  day:  31
dt.datetime(2020,7,31,0,0,0)
month:  7  day:  6
dt.datetime(2020,7,6,0,0,0)
month:  7  day:  13
dt.datetime(2020,7,13,0,0,0)
month:  7  day:  14
dt.datetime(2020,7,14,0,0,0)
month:  8  day:  15
dt.datetime(2020,8,15,0,0,0)
month:  8  day:  16
dt.datetime(2020,8,16,0,0,0)
month:  8  day:  17
dt.datetime(2020,8,17,0,0,0)
month:  8  day:  18
dt.datetime(2020,8,18,0,0,0)
month:  8  day:  19
dt.datetime(2020,8,19,0,0,0)
month:  8  day:  20
dt.datetime(2020,8,20,0,0,0)
month:  8  day:  21
dt.datetime(2020,8,21,0,0,0)
month:  8  day:  22
dt.datetime(2020,8,22,0,0,0)
month:  8  day:  23
dt.datetime(2020,8,23,0,0,0)
month:  8  day:  24
dt.datetime(2020,8,24,0,0,0)
month:  8  day:  25
dt.datetime(2020,8,25,0,0,0)
month:  8  day:  26
dt.datetime(2020,8,26,0,0,0)
month:  8  day:  27
dt.datetime(2020,8,27,0,0,0)
month:  8  day:  28
dt.datetime(2020,8,28,0,0,0)
month:  8  day:  29
dt.datetime(2020,8,29,0,0,0)
month:  8  day:  30
dt.datetime(2020,8,30,0,0,0)
month:  8  day:  31
dt.datetime(2020,8,31,0,0,0)
month:  8  day:  6
dt.datetime(2020,8,6,0,0,0)
month:  8  day:  13
dt.datetime(2020,8,13,0,0,0)
month:  8  day:  14
dt.datetime(2020,8,14,0,0,0)
month:  9  day:  15
dt.datetime(2020,9,15,0,0,0)
month:  9  day:  16
dt.datetime(2020,9,16,0,0,0)
month:  9  day:  17
dt.datetime(2020,9,17,0,0,0)
month:  9  day:  18
dt.datetime(2020,9,18,0,0,0)
month:  9  day:  19
dt.datetime(2020,9,19,0,0,0)
month:  9  day:  20
dt.datetime(2020,9,20,0,0,0)
month:  9  day:  21
dt.datetime(2020,9,21,0,0,0)
month:  9  day:  22
dt.datetime(2020,9,22,0,0,0)
month:  9  day:  23
dt.datetime(2020,9,23,0,0,0)
month:  9  day:  24
dt.datetime(2020,9,24,0,0,0)
month:  9  day:  25
dt.datetime(2020,9,25,0,0,0)
month:  9  day:  26
dt.datetime(2020,9,26,0,0,0)
month:  9  day:  27
dt.datetime(2020,9,27,0,0,0)
month:  9  day:  28
dt.datetime(2020,9,28,0,0,0)
month:  9  day:  29
dt.datetime(2020,9,29,0,0,0)
month:  9  day:  30
dt.datetime(2020,9,30,0,0,0)
month:  9  day:  31
dt.datetime(2020,9,31,0,0,0)
month:  9  day:  6
dt.datetime(2020,9,6,0,0,0)
month:  9  day:  13
dt.datetime(2020,9,13,0,0,0)
month:  9  day:  14
dt.datetime(2020,9,14,0,0,0)
month:  10  day:  15
dt.datetime(2020,10,15,0,0,0)
month:  10  day:  16
dt.datetime(2020,10,16,0,0,0)
month:  10  day:  17
dt.datetime(2020,10,17,0,0,0)
month:  10  day:  18
dt.datetime(2020,10,18,0,0,0)
month:  10  day:  19
dt.datetime(2020,10,19,0,0,0)
month:  10  day:  20
dt.datetime(2020,10,20,0,0,0)
month:  10  day:  21
dt.datetime(2020,10,21,0,0,0)
month:  10  day:  22
dt.datetime(2020,10,22,0,0,0)
month:  10  day:  23
dt.datetime(2020,10,23,0,0,0)
month:  10  day:  24
dt.datetime(2020,10,24,0,0,0)
month:  10  day:  25
dt.datetime(2020,10,25,0,0,0)
month:  10  day:  26
dt.datetime(2020,10,26,0,0,0)
month:  10  day:  27
dt.datetime(2020,10,27,0,0,0)
month:  10  day:  28
dt.datetime(2020,10,28,0,0,0)
month:  10  day:  29
dt.datetime(2020,10,29,0,0,0)
month:  10  day:  30
dt.datetime(2020,10,30,0,0,0)
month:  10  day:  31
dt.datetime(2020,10,31,0,0,0)
month:  10  day:  6
dt.datetime(2020,10,6,0,0,0)
month:  10  day:  13
dt.datetime(2020,10,13,0,0,0)
month:  10  day:  14
dt.datetime(2020,10,14,0,0,0)
month:  11  day:  15
dt.datetime(2020,11,15,0,0,0)
month:  11  day:  16
dt.datetime(2020,11,16,0,0,0)
month:  11  day:  17
dt.datetime(2020,11,17,0,0,0)
month:  11  day:  18
dt.datetime(2020,11,18,0,0,0)
month:  11  day:  19
dt.datetime(2020,11,19,0,0,0)
month:  11  day:  20
dt.datetime(2020,11,20,0,0,0)
month:  11  day:  21
dt.datetime(2020,11,21,0,0,0)
month:  11  day:  22
dt.datetime(2020,11,22,0,0,0)
month:  11  day:  23
dt.datetime(2020,11,23,0,0,0)
month:  11  day:  24
dt.datetime(2020,11,24,0,0,0)
month:  11  day:  25
dt.datetime(2020,11,25,0,0,0)
month:  11  day:  26
dt.datetime(2020,11,26,0,0,0)
month:  11  day:  27
dt.datetime(2020,11,27,0,0,0)
month:  11  day:  28
dt.datetime(2020,11,28,0,0,0)
month:  11  day:  29
dt.datetime(2020,11,29,0,0,0)
month:  11  day:  30
dt.datetime(2020,11,30,0,0,0)
month:  11  day:  31
dt.datetime(2020,11,31,0,0,0)
month:  11  day:  6
dt.datetime(2020,11,6,0,0,0)
month:  11  day:  13
dt.datetime(2020,11,13,0,0,0)
month:  11  day:  14
dt.datetime(2020,11,14,0,0,0)
month:  12  day:  15
dt.datetime(2020,12,15,0,0,0)
month:  12  day:  16
dt.datetime(2020,12,16,0,0,0)
month:  12  day:  17
dt.datetime(2020,12,17,0,0,0)
month:  12  day:  18
dt.datetime(2020,12,18,0,0,0)
month:  12  day:  19
dt.datetime(2020,12,19,0,0,0)
month:  12  day:  20
dt.datetime(2020,12,20,0,0,0)
month:  12  day:  21
dt.datetime(2020,12,21,0,0,0)
month:  12  day:  22
dt.datetime(2020,12,22,0,0,0)
month:  12  day:  23
dt.datetime(2020,12,23,0,0,0)
month:  12  day:  24
dt.datetime(2020,12,24,0,0,0)
month:  12  day:  25
dt.datetime(2020,12,25,0,0,0)
month:  12  day:  26
dt.datetime(2020,12,26,0,0,0)
month:  12  day:  27
dt.datetime(2020,12,27,0,0,0)
month:  12  day:  28
dt.datetime(2020,12,28,0,0,0)
month:  12  day:  29
dt.datetime(2020,12,29,0,0,0)
month:  12  day:  30
dt.datetime(2020,12,30,0,0,0)
month:  12  day:  31
dt.datetime(2020,12,31,0,0,0)
month:  12  day:  6
dt.datetime(2020,12,6,0,0,0)
month:  12  day:  13
dt.datetime(2020,12,13,0,0,0)
month:  12  day:  14
dt.datetime(2020,12,14,0,0,0)

In [ ]:
plantData = {
    "Plant1G": "../Data/Plant_1_Generation_Data.csv",
    "Plant1W": "../Data/Plant_1_Weather_Sensor_Data.csv",
    "Plant2G": "../Data/Plant_2_Generation_Data.csv",
    "Plant2W": "../Data/Plant_2_Weather_Sensor_Data.csv",
}